name: Deploy to EC2 production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd /var/www/college-street-online
            git fetch origin main
            git reset --hard origin/main
            composer install --no-dev --optimize-autoloader --ignore-platform-reqs
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            php artisan storage:link || true
            sudo chmod -R 775 storage bootstrap/cache
            sudo chown -R www-data:www-data storage bootstrap/cache